export const SIGNUP_INITIATION = 'SIGNUP_INITIATION';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const LOGIN_INITIATION = 'LOGIN_INITIATION';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT_INITIATION = 'LOGIN_INITIATION';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
